import re

def parse_content_plan_text(raw_text: str) -> list[dict]:
    """
    Parses the raw text content plan generated by the LLM into a list of dictionaries.

    Args:
        raw_text (str): The raw text output from the LLM, containing multiple
                        social media post ideas.

    Returns:
        list[dict]: A list of dictionaries, where each dictionary represents
                    a single social media post with its parsed details.
    """
    parsed_posts = []
    # Split the raw text into individual post blocks using '---' as a delimiter
    # This also handles potential leading/trailing empty strings from the split.
    post_blocks = [block.strip() for block in raw_text.split('---') if block.strip()]

    for block in post_blocks:
        post_data = {}
        lines = block.split('\n')
        
        # Iterate through lines and extract key-value pairs
        for line in lines:
            line = line.strip()
            if not line:
                continue # Skip empty lines

            # Regex to find "Key: Value" or "Key: Value (possibly multiline)"
            # This pattern is robust to handle multiline values like Image Generation Prompt
            match = re.match(r'^\*\*([A-Za-z0-9\s/]+?):\*\*\s*(.*)$', line)
            if match:
                key = match.group(1).strip().replace('_', ' ').title() # Normalize key names
                value = match.group(2).strip()
                post_data[key] = value
            elif post_data: # If it's a continuation of a multi-line value
                # This assumes the multiline part is immediately after a recognized key
                # and doesn't contain a new "Key: " pattern itself.
                last_key = list(post_data.keys())[-1]
                post_data[last_key] += "\n" + line.strip()

        # Clean up any potential empty string keys from initial regex matching issues
        # Or if the pattern didn't match perfectly, ensure we don't add empty entries.
        cleaned_post_data = {k: v.strip() for k, v in post_data.items() if k and v.strip()}
        
        if cleaned_post_data: # Only add if it's not an empty dictionary
            parsed_posts.append(cleaned_post_data)

    # Post-processing for Image Generation Prompt which might span multiple lines and
    # needs to be treated as a single block for the next step.
    for post in parsed_posts:
        if "Image Generation Prompt" in post:
            # Re-join lines for the prompt if it was split
            # The regex above should handle most, but this is a safeguard.
            prompt_lines = post["Image Generation Prompt"].split('\n')
            cleaned_prompt = []
            for pline in prompt_lines:
                # Remove any stray "Image Generation Prompt:" if it was repeated by LLM
                clean_pline = re.sub(r'Image Generation Prompt\s*:', '', pline, flags=re.IGNORECASE).strip()
                if clean_pline:
                    cleaned_prompt.append(clean_pline)
            post["Image Generation Prompt"] = " ".join(cleaned_prompt).strip()
            
            # Ensure "ONLY if Post Type is visual" and similar instructions are removed
            post["Image Generation Prompt"] = re.sub(r'\(ONLY if Post Type is visual\):\s*', '', post["Image Generation Prompt"], flags=re.IGNORECASE).strip()
            post["Image Generation Prompt"] = re.sub(r'If the Post Type is "Image Post" or "Short Video Concept" \(for a thumbnail/keyframe\),\s*', '', post["Image Generation Prompt"], flags=re.IGNORECASE).strip()
            post["Image Generation Prompt"] = re.sub(r'provide a highly detailed, specific, and creative prompt for an AI image generator \(like DALL-E 3\)\. This prompt should be ready to be directly sent to an image AI and reflect the Core Concept and Mock Trends\.\s*', '', post["Image Generation Prompt"], flags=re.IGNORECASE).strip()
            post["Image Generation Prompt"] = re.sub(r'\*Ensure this prompt is visually descriptive and includes style cues\.\*', '', post["Image Generation Prompt"], flags=re.IGNORECASE).strip()

            # A final check to remove any empty image prompt if the LLM output was just instructions
            if not post["Image Generation Prompt"].strip():
                post["Image Generation Prompt"] = ""

    return parsed_posts 